// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AppendEntries.proto

package com.github.cn.ccj.rpc;

public final class AppendEntries {
  private AppendEntries() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code raft.LogEntryType}
   */
  public enum LogEntryType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>EntryNormal = 0;</code>
     */
    EntryNormal(0),
    /**
     * <code>EntryConfig = 1;</code>
     */
    EntryConfig(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>EntryNormal = 0;</code>
     */
    public static final int EntryNormal_VALUE = 0;
    /**
     * <code>EntryConfig = 1;</code>
     */
    public static final int EntryConfig_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static LogEntryType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static LogEntryType forNumber(int value) {
      switch (value) {
        case 0: return EntryNormal;
        case 1: return EntryConfig;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<LogEntryType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        LogEntryType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<LogEntryType>() {
            public LogEntryType findValueByNumber(int number) {
              return LogEntryType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return AppendEntries.getDescriptor().getEnumTypes().get(0);
    }

    private static final LogEntryType[] VALUES = values();

    public static LogEntryType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private LogEntryType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:raft.LogEntryType)
  }

  public interface LogEntryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:raft.LogEntry)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint64 term = 1;</code>
     * @return The term.
     */
    long getTerm();

    /**
     * <code>uint64 index = 2;</code>
     * @return The index.
     */
    long getIndex();

    /**
     * <code>.raft.LogEntryType type = 3;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <code>.raft.LogEntryType type = 3;</code>
     * @return The type.
     */
    LogEntryType getType();

    /**
     * <code>bytes data = 4;</code>
     * @return The data.
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code raft.LogEntry}
   */
  public static final class LogEntry extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:raft.LogEntry)
      LogEntryOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LogEntry.newBuilder() to construct.
    private LogEntry(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LogEntry() {
      type_ = 0;
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new LogEntry();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private LogEntry(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              term_ = input.readUInt64();
              break;
            }
            case 16: {

              index_ = input.readUInt64();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 34: {

              data_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return AppendEntries.internal_static_raft_LogEntry_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return AppendEntries.internal_static_raft_LogEntry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              LogEntry.class, Builder.class);
    }

    public static final int TERM_FIELD_NUMBER = 1;
    private long term_;
    /**
     * <code>uint64 term = 1;</code>
     * @return The term.
     */
    @Override
    public long getTerm() {
      return term_;
    }

    public static final int INDEX_FIELD_NUMBER = 2;
    private long index_;
    /**
     * <code>uint64 index = 2;</code>
     * @return The index.
     */
    @Override
    public long getIndex() {
      return index_;
    }

    public static final int TYPE_FIELD_NUMBER = 3;
    private int type_;
    /**
     * <code>.raft.LogEntryType type = 3;</code>
     * @return The enum numeric value on the wire for type.
     */
    @Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.raft.LogEntryType type = 3;</code>
     * @return The type.
     */
    @Override public LogEntryType getType() {
      @SuppressWarnings("deprecation")
      LogEntryType result = LogEntryType.valueOf(type_);
      return result == null ? LogEntryType.UNRECOGNIZED : result;
    }

    public static final int DATA_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>bytes data = 4;</code>
     * @return The data.
     */
    @Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (term_ != 0L) {
        output.writeUInt64(1, term_);
      }
      if (index_ != 0L) {
        output.writeUInt64(2, index_);
      }
      if (type_ != LogEntryType.EntryNormal.getNumber()) {
        output.writeEnum(3, type_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(4, data_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (term_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, term_);
      }
      if (index_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, index_);
      }
      if (type_ != LogEntryType.EntryNormal.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, type_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, data_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof LogEntry)) {
        return super.equals(obj);
      }
      LogEntry other = (LogEntry) obj;

      if (getTerm()
          != other.getTerm()) return false;
      if (getIndex()
          != other.getIndex()) return false;
      if (type_ != other.type_) return false;
      if (!getData()
          .equals(other.getData())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TERM_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTerm());
      hash = (37 * hash) + INDEX_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getIndex());
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static LogEntry parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LogEntry parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LogEntry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LogEntry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LogEntry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LogEntry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LogEntry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static LogEntry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static LogEntry parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static LogEntry parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static LogEntry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static LogEntry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(LogEntry prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code raft.LogEntry}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:raft.LogEntry)
        LogEntryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return AppendEntries.internal_static_raft_LogEntry_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return AppendEntries.internal_static_raft_LogEntry_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                LogEntry.class, Builder.class);
      }

      // Construct using com.github.cn.ccj.rpc.AppendEntries.LogEntry.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        term_ = 0L;

        index_ = 0L;

        type_ = 0;

        data_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return AppendEntries.internal_static_raft_LogEntry_descriptor;
      }

      @Override
      public LogEntry getDefaultInstanceForType() {
        return LogEntry.getDefaultInstance();
      }

      @Override
      public LogEntry build() {
        LogEntry result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public LogEntry buildPartial() {
        LogEntry result = new LogEntry(this);
        result.term_ = term_;
        result.index_ = index_;
        result.type_ = type_;
        result.data_ = data_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof LogEntry) {
          return mergeFrom((LogEntry)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(LogEntry other) {
        if (other == LogEntry.getDefaultInstance()) return this;
        if (other.getTerm() != 0L) {
          setTerm(other.getTerm());
        }
        if (other.getIndex() != 0L) {
          setIndex(other.getIndex());
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        LogEntry parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (LogEntry) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long term_ ;
      /**
       * <code>uint64 term = 1;</code>
       * @return The term.
       */
      @Override
      public long getTerm() {
        return term_;
      }
      /**
       * <code>uint64 term = 1;</code>
       * @param value The term to set.
       * @return This builder for chaining.
       */
      public Builder setTerm(long value) {
        
        term_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 term = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTerm() {
        
        term_ = 0L;
        onChanged();
        return this;
      }

      private long index_ ;
      /**
       * <code>uint64 index = 2;</code>
       * @return The index.
       */
      @Override
      public long getIndex() {
        return index_;
      }
      /**
       * <code>uint64 index = 2;</code>
       * @param value The index to set.
       * @return This builder for chaining.
       */
      public Builder setIndex(long value) {
        
        index_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 index = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearIndex() {
        
        index_ = 0L;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <code>.raft.LogEntryType type = 3;</code>
       * @return The enum numeric value on the wire for type.
       */
      @Override public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.raft.LogEntryType type = 3;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.raft.LogEntryType type = 3;</code>
       * @return The type.
       */
      @Override
      public LogEntryType getType() {
        @SuppressWarnings("deprecation")
        LogEntryType result = LogEntryType.valueOf(type_);
        return result == null ? LogEntryType.UNRECOGNIZED : result;
      }
      /**
       * <code>.raft.LogEntryType type = 3;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(LogEntryType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.raft.LogEntryType type = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes data = 4;</code>
       * @return The data.
       */
      @Override
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>bytes data = 4;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes data = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:raft.LogEntry)
    }

    // @@protoc_insertion_point(class_scope:raft.LogEntry)
    private static final LogEntry DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new LogEntry();
    }

    public static LogEntry getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LogEntry>
        PARSER = new com.google.protobuf.AbstractParser<LogEntry>() {
      @Override
      public LogEntry parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LogEntry(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LogEntry> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<LogEntry> getParserForType() {
      return PARSER;
    }

    @Override
    public LogEntry getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AppendEntriesRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:raft.AppendEntriesRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint64 term = 1;</code>
     * @return The term.
     */
    long getTerm();

    /**
     * <code>uint64 leaderId = 2;</code>
     * @return The leaderId.
     */
    long getLeaderId();

    /**
     * <code>uint64 prevLogIndex = 3;</code>
     * @return The prevLogIndex.
     */
    long getPrevLogIndex();

    /**
     * <code>uint64 prevLogTerm = 4;</code>
     * @return The prevLogTerm.
     */
    long getPrevLogTerm();

    /**
     * <code>uint64 commitIndex = 5;</code>
     * @return The commitIndex.
     */
    long getCommitIndex();

    /**
     * <code>repeated .raft.LogEntry entries = 6;</code>
     */
    java.util.List<LogEntry>
        getEntriesList();
    /**
     * <code>repeated .raft.LogEntry entries = 6;</code>
     */
    LogEntry getEntries(int index);
    /**
     * <code>repeated .raft.LogEntry entries = 6;</code>
     */
    int getEntriesCount();
    /**
     * <code>repeated .raft.LogEntry entries = 6;</code>
     */
    java.util.List<? extends LogEntryOrBuilder>
        getEntriesOrBuilderList();
    /**
     * <code>repeated .raft.LogEntry entries = 6;</code>
     */
    LogEntryOrBuilder getEntriesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code raft.AppendEntriesRequest}
   */
  public static final class AppendEntriesRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:raft.AppendEntriesRequest)
      AppendEntriesRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AppendEntriesRequest.newBuilder() to construct.
    private AppendEntriesRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AppendEntriesRequest() {
      entries_ = java.util.Collections.emptyList();
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new AppendEntriesRequest();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AppendEntriesRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              term_ = input.readUInt64();
              break;
            }
            case 16: {

              leaderId_ = input.readUInt64();
              break;
            }
            case 24: {

              prevLogIndex_ = input.readUInt64();
              break;
            }
            case 32: {

              prevLogTerm_ = input.readUInt64();
              break;
            }
            case 40: {

              commitIndex_ = input.readUInt64();
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                entries_ = new java.util.ArrayList<LogEntry>();
                mutable_bitField0_ |= 0x00000001;
              }
              entries_.add(
                  input.readMessage(LogEntry.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          entries_ = java.util.Collections.unmodifiableList(entries_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return AppendEntries.internal_static_raft_AppendEntriesRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return AppendEntries.internal_static_raft_AppendEntriesRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              AppendEntriesRequest.class, Builder.class);
    }

    public static final int TERM_FIELD_NUMBER = 1;
    private long term_;
    /**
     * <code>uint64 term = 1;</code>
     * @return The term.
     */
    @Override
    public long getTerm() {
      return term_;
    }

    public static final int LEADERID_FIELD_NUMBER = 2;
    private long leaderId_;
    /**
     * <code>uint64 leaderId = 2;</code>
     * @return The leaderId.
     */
    @Override
    public long getLeaderId() {
      return leaderId_;
    }

    public static final int PREVLOGINDEX_FIELD_NUMBER = 3;
    private long prevLogIndex_;
    /**
     * <code>uint64 prevLogIndex = 3;</code>
     * @return The prevLogIndex.
     */
    @Override
    public long getPrevLogIndex() {
      return prevLogIndex_;
    }

    public static final int PREVLOGTERM_FIELD_NUMBER = 4;
    private long prevLogTerm_;
    /**
     * <code>uint64 prevLogTerm = 4;</code>
     * @return The prevLogTerm.
     */
    @Override
    public long getPrevLogTerm() {
      return prevLogTerm_;
    }

    public static final int COMMITINDEX_FIELD_NUMBER = 5;
    private long commitIndex_;
    /**
     * <code>uint64 commitIndex = 5;</code>
     * @return The commitIndex.
     */
    @Override
    public long getCommitIndex() {
      return commitIndex_;
    }

    public static final int ENTRIES_FIELD_NUMBER = 6;
    private java.util.List<LogEntry> entries_;
    /**
     * <code>repeated .raft.LogEntry entries = 6;</code>
     */
    @Override
    public java.util.List<LogEntry> getEntriesList() {
      return entries_;
    }
    /**
     * <code>repeated .raft.LogEntry entries = 6;</code>
     */
    @Override
    public java.util.List<? extends LogEntryOrBuilder>
        getEntriesOrBuilderList() {
      return entries_;
    }
    /**
     * <code>repeated .raft.LogEntry entries = 6;</code>
     */
    @Override
    public int getEntriesCount() {
      return entries_.size();
    }
    /**
     * <code>repeated .raft.LogEntry entries = 6;</code>
     */
    @Override
    public LogEntry getEntries(int index) {
      return entries_.get(index);
    }
    /**
     * <code>repeated .raft.LogEntry entries = 6;</code>
     */
    @Override
    public LogEntryOrBuilder getEntriesOrBuilder(
        int index) {
      return entries_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (term_ != 0L) {
        output.writeUInt64(1, term_);
      }
      if (leaderId_ != 0L) {
        output.writeUInt64(2, leaderId_);
      }
      if (prevLogIndex_ != 0L) {
        output.writeUInt64(3, prevLogIndex_);
      }
      if (prevLogTerm_ != 0L) {
        output.writeUInt64(4, prevLogTerm_);
      }
      if (commitIndex_ != 0L) {
        output.writeUInt64(5, commitIndex_);
      }
      for (int i = 0; i < entries_.size(); i++) {
        output.writeMessage(6, entries_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (term_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, term_);
      }
      if (leaderId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, leaderId_);
      }
      if (prevLogIndex_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, prevLogIndex_);
      }
      if (prevLogTerm_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, prevLogTerm_);
      }
      if (commitIndex_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(5, commitIndex_);
      }
      for (int i = 0; i < entries_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, entries_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof AppendEntriesRequest)) {
        return super.equals(obj);
      }
      AppendEntriesRequest other = (AppendEntriesRequest) obj;

      if (getTerm()
          != other.getTerm()) return false;
      if (getLeaderId()
          != other.getLeaderId()) return false;
      if (getPrevLogIndex()
          != other.getPrevLogIndex()) return false;
      if (getPrevLogTerm()
          != other.getPrevLogTerm()) return false;
      if (getCommitIndex()
          != other.getCommitIndex()) return false;
      if (!getEntriesList()
          .equals(other.getEntriesList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TERM_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTerm());
      hash = (37 * hash) + LEADERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLeaderId());
      hash = (37 * hash) + PREVLOGINDEX_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPrevLogIndex());
      hash = (37 * hash) + PREVLOGTERM_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPrevLogTerm());
      hash = (37 * hash) + COMMITINDEX_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCommitIndex());
      if (getEntriesCount() > 0) {
        hash = (37 * hash) + ENTRIES_FIELD_NUMBER;
        hash = (53 * hash) + getEntriesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static AppendEntriesRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AppendEntriesRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AppendEntriesRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AppendEntriesRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AppendEntriesRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AppendEntriesRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AppendEntriesRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AppendEntriesRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static AppendEntriesRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static AppendEntriesRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static AppendEntriesRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AppendEntriesRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(AppendEntriesRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code raft.AppendEntriesRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:raft.AppendEntriesRequest)
        AppendEntriesRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return AppendEntries.internal_static_raft_AppendEntriesRequest_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return AppendEntries.internal_static_raft_AppendEntriesRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                AppendEntriesRequest.class, Builder.class);
      }

      // Construct using com.github.cn.ccj.rpc.AppendEntries.AppendEntriesRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getEntriesFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        term_ = 0L;

        leaderId_ = 0L;

        prevLogIndex_ = 0L;

        prevLogTerm_ = 0L;

        commitIndex_ = 0L;

        if (entriesBuilder_ == null) {
          entries_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          entriesBuilder_.clear();
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return AppendEntries.internal_static_raft_AppendEntriesRequest_descriptor;
      }

      @Override
      public AppendEntriesRequest getDefaultInstanceForType() {
        return AppendEntriesRequest.getDefaultInstance();
      }

      @Override
      public AppendEntriesRequest build() {
        AppendEntriesRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public AppendEntriesRequest buildPartial() {
        AppendEntriesRequest result = new AppendEntriesRequest(this);
        int from_bitField0_ = bitField0_;
        result.term_ = term_;
        result.leaderId_ = leaderId_;
        result.prevLogIndex_ = prevLogIndex_;
        result.prevLogTerm_ = prevLogTerm_;
        result.commitIndex_ = commitIndex_;
        if (entriesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            entries_ = java.util.Collections.unmodifiableList(entries_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.entries_ = entries_;
        } else {
          result.entries_ = entriesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof AppendEntriesRequest) {
          return mergeFrom((AppendEntriesRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(AppendEntriesRequest other) {
        if (other == AppendEntriesRequest.getDefaultInstance()) return this;
        if (other.getTerm() != 0L) {
          setTerm(other.getTerm());
        }
        if (other.getLeaderId() != 0L) {
          setLeaderId(other.getLeaderId());
        }
        if (other.getPrevLogIndex() != 0L) {
          setPrevLogIndex(other.getPrevLogIndex());
        }
        if (other.getPrevLogTerm() != 0L) {
          setPrevLogTerm(other.getPrevLogTerm());
        }
        if (other.getCommitIndex() != 0L) {
          setCommitIndex(other.getCommitIndex());
        }
        if (entriesBuilder_ == null) {
          if (!other.entries_.isEmpty()) {
            if (entries_.isEmpty()) {
              entries_ = other.entries_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureEntriesIsMutable();
              entries_.addAll(other.entries_);
            }
            onChanged();
          }
        } else {
          if (!other.entries_.isEmpty()) {
            if (entriesBuilder_.isEmpty()) {
              entriesBuilder_.dispose();
              entriesBuilder_ = null;
              entries_ = other.entries_;
              bitField0_ = (bitField0_ & ~0x00000001);
              entriesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getEntriesFieldBuilder() : null;
            } else {
              entriesBuilder_.addAllMessages(other.entries_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        AppendEntriesRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (AppendEntriesRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long term_ ;
      /**
       * <code>uint64 term = 1;</code>
       * @return The term.
       */
      @Override
      public long getTerm() {
        return term_;
      }
      /**
       * <code>uint64 term = 1;</code>
       * @param value The term to set.
       * @return This builder for chaining.
       */
      public Builder setTerm(long value) {
        
        term_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 term = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTerm() {
        
        term_ = 0L;
        onChanged();
        return this;
      }

      private long leaderId_ ;
      /**
       * <code>uint64 leaderId = 2;</code>
       * @return The leaderId.
       */
      @Override
      public long getLeaderId() {
        return leaderId_;
      }
      /**
       * <code>uint64 leaderId = 2;</code>
       * @param value The leaderId to set.
       * @return This builder for chaining.
       */
      public Builder setLeaderId(long value) {
        
        leaderId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 leaderId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLeaderId() {
        
        leaderId_ = 0L;
        onChanged();
        return this;
      }

      private long prevLogIndex_ ;
      /**
       * <code>uint64 prevLogIndex = 3;</code>
       * @return The prevLogIndex.
       */
      @Override
      public long getPrevLogIndex() {
        return prevLogIndex_;
      }
      /**
       * <code>uint64 prevLogIndex = 3;</code>
       * @param value The prevLogIndex to set.
       * @return This builder for chaining.
       */
      public Builder setPrevLogIndex(long value) {
        
        prevLogIndex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 prevLogIndex = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPrevLogIndex() {
        
        prevLogIndex_ = 0L;
        onChanged();
        return this;
      }

      private long prevLogTerm_ ;
      /**
       * <code>uint64 prevLogTerm = 4;</code>
       * @return The prevLogTerm.
       */
      @Override
      public long getPrevLogTerm() {
        return prevLogTerm_;
      }
      /**
       * <code>uint64 prevLogTerm = 4;</code>
       * @param value The prevLogTerm to set.
       * @return This builder for chaining.
       */
      public Builder setPrevLogTerm(long value) {
        
        prevLogTerm_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 prevLogTerm = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearPrevLogTerm() {
        
        prevLogTerm_ = 0L;
        onChanged();
        return this;
      }

      private long commitIndex_ ;
      /**
       * <code>uint64 commitIndex = 5;</code>
       * @return The commitIndex.
       */
      @Override
      public long getCommitIndex() {
        return commitIndex_;
      }
      /**
       * <code>uint64 commitIndex = 5;</code>
       * @param value The commitIndex to set.
       * @return This builder for chaining.
       */
      public Builder setCommitIndex(long value) {
        
        commitIndex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 commitIndex = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearCommitIndex() {
        
        commitIndex_ = 0L;
        onChanged();
        return this;
      }

      private java.util.List<LogEntry> entries_ =
        java.util.Collections.emptyList();
      private void ensureEntriesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          entries_ = new java.util.ArrayList<LogEntry>(entries_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          LogEntry, LogEntry.Builder, LogEntryOrBuilder> entriesBuilder_;

      /**
       * <code>repeated .raft.LogEntry entries = 6;</code>
       */
      public java.util.List<LogEntry> getEntriesList() {
        if (entriesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(entries_);
        } else {
          return entriesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .raft.LogEntry entries = 6;</code>
       */
      public int getEntriesCount() {
        if (entriesBuilder_ == null) {
          return entries_.size();
        } else {
          return entriesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .raft.LogEntry entries = 6;</code>
       */
      public LogEntry getEntries(int index) {
        if (entriesBuilder_ == null) {
          return entries_.get(index);
        } else {
          return entriesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .raft.LogEntry entries = 6;</code>
       */
      public Builder setEntries(
          int index, LogEntry value) {
        if (entriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEntriesIsMutable();
          entries_.set(index, value);
          onChanged();
        } else {
          entriesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .raft.LogEntry entries = 6;</code>
       */
      public Builder setEntries(
          int index, LogEntry.Builder builderForValue) {
        if (entriesBuilder_ == null) {
          ensureEntriesIsMutable();
          entries_.set(index, builderForValue.build());
          onChanged();
        } else {
          entriesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .raft.LogEntry entries = 6;</code>
       */
      public Builder addEntries(LogEntry value) {
        if (entriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEntriesIsMutable();
          entries_.add(value);
          onChanged();
        } else {
          entriesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .raft.LogEntry entries = 6;</code>
       */
      public Builder addEntries(
          int index, LogEntry value) {
        if (entriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEntriesIsMutable();
          entries_.add(index, value);
          onChanged();
        } else {
          entriesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .raft.LogEntry entries = 6;</code>
       */
      public Builder addEntries(
          LogEntry.Builder builderForValue) {
        if (entriesBuilder_ == null) {
          ensureEntriesIsMutable();
          entries_.add(builderForValue.build());
          onChanged();
        } else {
          entriesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .raft.LogEntry entries = 6;</code>
       */
      public Builder addEntries(
          int index, LogEntry.Builder builderForValue) {
        if (entriesBuilder_ == null) {
          ensureEntriesIsMutable();
          entries_.add(index, builderForValue.build());
          onChanged();
        } else {
          entriesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .raft.LogEntry entries = 6;</code>
       */
      public Builder addAllEntries(
          Iterable<? extends LogEntry> values) {
        if (entriesBuilder_ == null) {
          ensureEntriesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, entries_);
          onChanged();
        } else {
          entriesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .raft.LogEntry entries = 6;</code>
       */
      public Builder clearEntries() {
        if (entriesBuilder_ == null) {
          entries_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          entriesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .raft.LogEntry entries = 6;</code>
       */
      public Builder removeEntries(int index) {
        if (entriesBuilder_ == null) {
          ensureEntriesIsMutable();
          entries_.remove(index);
          onChanged();
        } else {
          entriesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .raft.LogEntry entries = 6;</code>
       */
      public LogEntry.Builder getEntriesBuilder(
          int index) {
        return getEntriesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .raft.LogEntry entries = 6;</code>
       */
      public LogEntryOrBuilder getEntriesOrBuilder(
          int index) {
        if (entriesBuilder_ == null) {
          return entries_.get(index);  } else {
          return entriesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .raft.LogEntry entries = 6;</code>
       */
      public java.util.List<? extends LogEntryOrBuilder>
           getEntriesOrBuilderList() {
        if (entriesBuilder_ != null) {
          return entriesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(entries_);
        }
      }
      /**
       * <code>repeated .raft.LogEntry entries = 6;</code>
       */
      public LogEntry.Builder addEntriesBuilder() {
        return getEntriesFieldBuilder().addBuilder(
            LogEntry.getDefaultInstance());
      }
      /**
       * <code>repeated .raft.LogEntry entries = 6;</code>
       */
      public LogEntry.Builder addEntriesBuilder(
          int index) {
        return getEntriesFieldBuilder().addBuilder(
            index, LogEntry.getDefaultInstance());
      }
      /**
       * <code>repeated .raft.LogEntry entries = 6;</code>
       */
      public java.util.List<LogEntry.Builder>
           getEntriesBuilderList() {
        return getEntriesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          LogEntry, LogEntry.Builder, LogEntryOrBuilder>
          getEntriesFieldBuilder() {
        if (entriesBuilder_ == null) {
          entriesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              LogEntry, LogEntry.Builder, LogEntryOrBuilder>(
                  entries_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          entries_ = null;
        }
        return entriesBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:raft.AppendEntriesRequest)
    }

    // @@protoc_insertion_point(class_scope:raft.AppendEntriesRequest)
    private static final AppendEntriesRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new AppendEntriesRequest();
    }

    public static AppendEntriesRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AppendEntriesRequest>
        PARSER = new com.google.protobuf.AbstractParser<AppendEntriesRequest>() {
      @Override
      public AppendEntriesRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AppendEntriesRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AppendEntriesRequest> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<AppendEntriesRequest> getParserForType() {
      return PARSER;
    }

    @Override
    public AppendEntriesRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AppendEntriesResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:raft.AppendEntriesResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint64 term = 1;</code>
     * @return The term.
     */
    long getTerm();

    /**
     * <code>bool success = 2;</code>
     * @return The success.
     */
    boolean getSuccess();

    /**
     * <code>uint64 LastLogIndex = 3;</code>
     * @return The lastLogIndex.
     */
    long getLastLogIndex();
  }
  /**
   * Protobuf type {@code raft.AppendEntriesResponse}
   */
  public static final class AppendEntriesResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:raft.AppendEntriesResponse)
      AppendEntriesResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AppendEntriesResponse.newBuilder() to construct.
    private AppendEntriesResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AppendEntriesResponse() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new AppendEntriesResponse();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AppendEntriesResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              term_ = input.readUInt64();
              break;
            }
            case 16: {

              success_ = input.readBool();
              break;
            }
            case 24: {

              lastLogIndex_ = input.readUInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return AppendEntries.internal_static_raft_AppendEntriesResponse_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return AppendEntries.internal_static_raft_AppendEntriesResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              AppendEntriesResponse.class, Builder.class);
    }

    public static final int TERM_FIELD_NUMBER = 1;
    private long term_;
    /**
     * <code>uint64 term = 1;</code>
     * @return The term.
     */
    @Override
    public long getTerm() {
      return term_;
    }

    public static final int SUCCESS_FIELD_NUMBER = 2;
    private boolean success_;
    /**
     * <code>bool success = 2;</code>
     * @return The success.
     */
    @Override
    public boolean getSuccess() {
      return success_;
    }

    public static final int LASTLOGINDEX_FIELD_NUMBER = 3;
    private long lastLogIndex_;
    /**
     * <code>uint64 LastLogIndex = 3;</code>
     * @return The lastLogIndex.
     */
    @Override
    public long getLastLogIndex() {
      return lastLogIndex_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (term_ != 0L) {
        output.writeUInt64(1, term_);
      }
      if (success_ != false) {
        output.writeBool(2, success_);
      }
      if (lastLogIndex_ != 0L) {
        output.writeUInt64(3, lastLogIndex_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (term_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, term_);
      }
      if (success_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, success_);
      }
      if (lastLogIndex_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, lastLogIndex_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof AppendEntriesResponse)) {
        return super.equals(obj);
      }
      AppendEntriesResponse other = (AppendEntriesResponse) obj;

      if (getTerm()
          != other.getTerm()) return false;
      if (getSuccess()
          != other.getSuccess()) return false;
      if (getLastLogIndex()
          != other.getLastLogIndex()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TERM_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTerm());
      hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSuccess());
      hash = (37 * hash) + LASTLOGINDEX_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLastLogIndex());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static AppendEntriesResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AppendEntriesResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AppendEntriesResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AppendEntriesResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AppendEntriesResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AppendEntriesResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AppendEntriesResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AppendEntriesResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static AppendEntriesResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static AppendEntriesResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static AppendEntriesResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AppendEntriesResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(AppendEntriesResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code raft.AppendEntriesResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:raft.AppendEntriesResponse)
        AppendEntriesResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return AppendEntries.internal_static_raft_AppendEntriesResponse_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return AppendEntries.internal_static_raft_AppendEntriesResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                AppendEntriesResponse.class, Builder.class);
      }

      // Construct using com.github.cn.ccj.rpc.AppendEntries.AppendEntriesResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        term_ = 0L;

        success_ = false;

        lastLogIndex_ = 0L;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return AppendEntries.internal_static_raft_AppendEntriesResponse_descriptor;
      }

      @Override
      public AppendEntriesResponse getDefaultInstanceForType() {
        return AppendEntriesResponse.getDefaultInstance();
      }

      @Override
      public AppendEntriesResponse build() {
        AppendEntriesResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public AppendEntriesResponse buildPartial() {
        AppendEntriesResponse result = new AppendEntriesResponse(this);
        result.term_ = term_;
        result.success_ = success_;
        result.lastLogIndex_ = lastLogIndex_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof AppendEntriesResponse) {
          return mergeFrom((AppendEntriesResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(AppendEntriesResponse other) {
        if (other == AppendEntriesResponse.getDefaultInstance()) return this;
        if (other.getTerm() != 0L) {
          setTerm(other.getTerm());
        }
        if (other.getSuccess() != false) {
          setSuccess(other.getSuccess());
        }
        if (other.getLastLogIndex() != 0L) {
          setLastLogIndex(other.getLastLogIndex());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        AppendEntriesResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (AppendEntriesResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long term_ ;
      /**
       * <code>uint64 term = 1;</code>
       * @return The term.
       */
      @Override
      public long getTerm() {
        return term_;
      }
      /**
       * <code>uint64 term = 1;</code>
       * @param value The term to set.
       * @return This builder for chaining.
       */
      public Builder setTerm(long value) {
        
        term_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 term = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTerm() {
        
        term_ = 0L;
        onChanged();
        return this;
      }

      private boolean success_ ;
      /**
       * <code>bool success = 2;</code>
       * @return The success.
       */
      @Override
      public boolean getSuccess() {
        return success_;
      }
      /**
       * <code>bool success = 2;</code>
       * @param value The success to set.
       * @return This builder for chaining.
       */
      public Builder setSuccess(boolean value) {
        
        success_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool success = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSuccess() {
        
        success_ = false;
        onChanged();
        return this;
      }

      private long lastLogIndex_ ;
      /**
       * <code>uint64 LastLogIndex = 3;</code>
       * @return The lastLogIndex.
       */
      @Override
      public long getLastLogIndex() {
        return lastLogIndex_;
      }
      /**
       * <code>uint64 LastLogIndex = 3;</code>
       * @param value The lastLogIndex to set.
       * @return This builder for chaining.
       */
      public Builder setLastLogIndex(long value) {
        
        lastLogIndex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 LastLogIndex = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearLastLogIndex() {
        
        lastLogIndex_ = 0L;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:raft.AppendEntriesResponse)
    }

    // @@protoc_insertion_point(class_scope:raft.AppendEntriesResponse)
    private static final AppendEntriesResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new AppendEntriesResponse();
    }

    public static AppendEntriesResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AppendEntriesResponse>
        PARSER = new com.google.protobuf.AbstractParser<AppendEntriesResponse>() {
      @Override
      public AppendEntriesResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AppendEntriesResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AppendEntriesResponse> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<AppendEntriesResponse> getParserForType() {
      return PARSER;
    }

    @Override
    public AppendEntriesResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_raft_LogEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_raft_LogEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_raft_AppendEntriesRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_raft_AppendEntriesRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_raft_AppendEntriesResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_raft_AppendEntriesResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\023AppendEntries.proto\022\004raft\"W\n\010LogEntry\022" +
      "\014\n\004term\030\001 \001(\004\022\r\n\005index\030\002 \001(\004\022 \n\004type\030\003 \001" +
      "(\0162\022.raft.LogEntryType\022\014\n\004data\030\004 \001(\014\"\227\001\n" +
      "\024AppendEntriesRequest\022\014\n\004term\030\001 \001(\004\022\020\n\010l" +
      "eaderId\030\002 \001(\004\022\024\n\014prevLogIndex\030\003 \001(\004\022\023\n\013p" +
      "revLogTerm\030\004 \001(\004\022\023\n\013commitIndex\030\005 \001(\004\022\037\n" +
      "\007entries\030\006 \003(\0132\016.raft.LogEntry\"L\n\025Append" +
      "EntriesResponse\022\014\n\004term\030\001 \001(\004\022\017\n\007success" +
      "\030\002 \001(\010\022\024\n\014LastLogIndex\030\003 \001(\004*0\n\014LogEntry" +
      "Type\022\017\n\013EntryNormal\020\000\022\017\n\013EntryConfig\020\0012`" +
      "\n\024AppendEntriesService\022H\n\rappendEntries\022" +
      "\032.raft.AppendEntriesRequest\032\033.raft.Appen" +
      "dEntriesResponseB\031\n\025com.github.cn.ccj.rp" +
      "cP\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_raft_LogEntry_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_raft_LogEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_raft_LogEntry_descriptor,
        new String[] { "Term", "Index", "Type", "Data", });
    internal_static_raft_AppendEntriesRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_raft_AppendEntriesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_raft_AppendEntriesRequest_descriptor,
        new String[] { "Term", "LeaderId", "PrevLogIndex", "PrevLogTerm", "CommitIndex", "Entries", });
    internal_static_raft_AppendEntriesResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_raft_AppendEntriesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_raft_AppendEntriesResponse_descriptor,
        new String[] { "Term", "Success", "LastLogIndex", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
