// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: InstallSnapshot.proto

package com.github.cn.ccj.rpc;

public final class InstallSnapshot {
  private InstallSnapshot() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface InstallSnapshotRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:raft.InstallSnapshotRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint64 term = 1;</code>
     * @return The term.
     */
    long getTerm();

    /**
     * <code>uint64 leaderId = 2;</code>
     * @return The leaderId.
     */
    long getLeaderId();

    /**
     * <code>uint64 lastLogIndex = 3;</code>
     * @return The lastLogIndex.
     */
    long getLastLogIndex();

    /**
     * <code>uint64 lastLogTerm = 4;</code>
     * @return The lastLogTerm.
     */
    long getLastLogTerm();

    /**
     * <code>bytes configuration = 5;</code>
     * @return The configuration.
     */
    com.google.protobuf.ByteString getConfiguration();

    /**
     * <code>uint64 configurationIndex = 6;</code>
     * @return The configurationIndex.
     */
    long getConfigurationIndex();

    /**
     * <code>uint64 size = 7;</code>
     * @return The size.
     */
    long getSize();
  }
  /**
   * Protobuf type {@code raft.InstallSnapshotRequest}
   */
  public static final class InstallSnapshotRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:raft.InstallSnapshotRequest)
      InstallSnapshotRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use InstallSnapshotRequest.newBuilder() to construct.
    private InstallSnapshotRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private InstallSnapshotRequest() {
      configuration_ = com.google.protobuf.ByteString.EMPTY;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new InstallSnapshotRequest();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private InstallSnapshotRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              term_ = input.readUInt64();
              break;
            }
            case 16: {

              leaderId_ = input.readUInt64();
              break;
            }
            case 24: {

              lastLogIndex_ = input.readUInt64();
              break;
            }
            case 32: {

              lastLogTerm_ = input.readUInt64();
              break;
            }
            case 42: {

              configuration_ = input.readBytes();
              break;
            }
            case 48: {

              configurationIndex_ = input.readUInt64();
              break;
            }
            case 56: {

              size_ = input.readUInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return InstallSnapshot.internal_static_raft_InstallSnapshotRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return InstallSnapshot.internal_static_raft_InstallSnapshotRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              InstallSnapshotRequest.class, Builder.class);
    }

    public static final int TERM_FIELD_NUMBER = 1;
    private long term_;
    /**
     * <code>uint64 term = 1;</code>
     * @return The term.
     */
    @Override
    public long getTerm() {
      return term_;
    }

    public static final int LEADERID_FIELD_NUMBER = 2;
    private long leaderId_;
    /**
     * <code>uint64 leaderId = 2;</code>
     * @return The leaderId.
     */
    @Override
    public long getLeaderId() {
      return leaderId_;
    }

    public static final int LASTLOGINDEX_FIELD_NUMBER = 3;
    private long lastLogIndex_;
    /**
     * <code>uint64 lastLogIndex = 3;</code>
     * @return The lastLogIndex.
     */
    @Override
    public long getLastLogIndex() {
      return lastLogIndex_;
    }

    public static final int LASTLOGTERM_FIELD_NUMBER = 4;
    private long lastLogTerm_;
    /**
     * <code>uint64 lastLogTerm = 4;</code>
     * @return The lastLogTerm.
     */
    @Override
    public long getLastLogTerm() {
      return lastLogTerm_;
    }

    public static final int CONFIGURATION_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString configuration_;
    /**
     * <code>bytes configuration = 5;</code>
     * @return The configuration.
     */
    @Override
    public com.google.protobuf.ByteString getConfiguration() {
      return configuration_;
    }

    public static final int CONFIGURATIONINDEX_FIELD_NUMBER = 6;
    private long configurationIndex_;
    /**
     * <code>uint64 configurationIndex = 6;</code>
     * @return The configurationIndex.
     */
    @Override
    public long getConfigurationIndex() {
      return configurationIndex_;
    }

    public static final int SIZE_FIELD_NUMBER = 7;
    private long size_;
    /**
     * <code>uint64 size = 7;</code>
     * @return The size.
     */
    @Override
    public long getSize() {
      return size_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (term_ != 0L) {
        output.writeUInt64(1, term_);
      }
      if (leaderId_ != 0L) {
        output.writeUInt64(2, leaderId_);
      }
      if (lastLogIndex_ != 0L) {
        output.writeUInt64(3, lastLogIndex_);
      }
      if (lastLogTerm_ != 0L) {
        output.writeUInt64(4, lastLogTerm_);
      }
      if (!configuration_.isEmpty()) {
        output.writeBytes(5, configuration_);
      }
      if (configurationIndex_ != 0L) {
        output.writeUInt64(6, configurationIndex_);
      }
      if (size_ != 0L) {
        output.writeUInt64(7, size_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (term_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, term_);
      }
      if (leaderId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, leaderId_);
      }
      if (lastLogIndex_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, lastLogIndex_);
      }
      if (lastLogTerm_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, lastLogTerm_);
      }
      if (!configuration_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, configuration_);
      }
      if (configurationIndex_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(6, configurationIndex_);
      }
      if (size_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(7, size_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof InstallSnapshotRequest)) {
        return super.equals(obj);
      }
      InstallSnapshotRequest other = (InstallSnapshotRequest) obj;

      if (getTerm()
          != other.getTerm()) return false;
      if (getLeaderId()
          != other.getLeaderId()) return false;
      if (getLastLogIndex()
          != other.getLastLogIndex()) return false;
      if (getLastLogTerm()
          != other.getLastLogTerm()) return false;
      if (!getConfiguration()
          .equals(other.getConfiguration())) return false;
      if (getConfigurationIndex()
          != other.getConfigurationIndex()) return false;
      if (getSize()
          != other.getSize()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TERM_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTerm());
      hash = (37 * hash) + LEADERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLeaderId());
      hash = (37 * hash) + LASTLOGINDEX_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLastLogIndex());
      hash = (37 * hash) + LASTLOGTERM_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLastLogTerm());
      hash = (37 * hash) + CONFIGURATION_FIELD_NUMBER;
      hash = (53 * hash) + getConfiguration().hashCode();
      hash = (37 * hash) + CONFIGURATIONINDEX_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getConfigurationIndex());
      hash = (37 * hash) + SIZE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSize());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static InstallSnapshotRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static InstallSnapshotRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static InstallSnapshotRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static InstallSnapshotRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static InstallSnapshotRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static InstallSnapshotRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static InstallSnapshotRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static InstallSnapshotRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static InstallSnapshotRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static InstallSnapshotRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static InstallSnapshotRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static InstallSnapshotRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(InstallSnapshotRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code raft.InstallSnapshotRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:raft.InstallSnapshotRequest)
        InstallSnapshotRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return InstallSnapshot.internal_static_raft_InstallSnapshotRequest_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return InstallSnapshot.internal_static_raft_InstallSnapshotRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                InstallSnapshotRequest.class, Builder.class);
      }

      // Construct using com.github.cn.ccj.rpc.InstallSnapshot.InstallSnapshotRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        term_ = 0L;

        leaderId_ = 0L;

        lastLogIndex_ = 0L;

        lastLogTerm_ = 0L;

        configuration_ = com.google.protobuf.ByteString.EMPTY;

        configurationIndex_ = 0L;

        size_ = 0L;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return InstallSnapshot.internal_static_raft_InstallSnapshotRequest_descriptor;
      }

      @Override
      public InstallSnapshotRequest getDefaultInstanceForType() {
        return InstallSnapshotRequest.getDefaultInstance();
      }

      @Override
      public InstallSnapshotRequest build() {
        InstallSnapshotRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public InstallSnapshotRequest buildPartial() {
        InstallSnapshotRequest result = new InstallSnapshotRequest(this);
        result.term_ = term_;
        result.leaderId_ = leaderId_;
        result.lastLogIndex_ = lastLogIndex_;
        result.lastLogTerm_ = lastLogTerm_;
        result.configuration_ = configuration_;
        result.configurationIndex_ = configurationIndex_;
        result.size_ = size_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof InstallSnapshotRequest) {
          return mergeFrom((InstallSnapshotRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(InstallSnapshotRequest other) {
        if (other == InstallSnapshotRequest.getDefaultInstance()) return this;
        if (other.getTerm() != 0L) {
          setTerm(other.getTerm());
        }
        if (other.getLeaderId() != 0L) {
          setLeaderId(other.getLeaderId());
        }
        if (other.getLastLogIndex() != 0L) {
          setLastLogIndex(other.getLastLogIndex());
        }
        if (other.getLastLogTerm() != 0L) {
          setLastLogTerm(other.getLastLogTerm());
        }
        if (other.getConfiguration() != com.google.protobuf.ByteString.EMPTY) {
          setConfiguration(other.getConfiguration());
        }
        if (other.getConfigurationIndex() != 0L) {
          setConfigurationIndex(other.getConfigurationIndex());
        }
        if (other.getSize() != 0L) {
          setSize(other.getSize());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        InstallSnapshotRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (InstallSnapshotRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long term_ ;
      /**
       * <code>uint64 term = 1;</code>
       * @return The term.
       */
      @Override
      public long getTerm() {
        return term_;
      }
      /**
       * <code>uint64 term = 1;</code>
       * @param value The term to set.
       * @return This builder for chaining.
       */
      public Builder setTerm(long value) {
        
        term_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 term = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTerm() {
        
        term_ = 0L;
        onChanged();
        return this;
      }

      private long leaderId_ ;
      /**
       * <code>uint64 leaderId = 2;</code>
       * @return The leaderId.
       */
      @Override
      public long getLeaderId() {
        return leaderId_;
      }
      /**
       * <code>uint64 leaderId = 2;</code>
       * @param value The leaderId to set.
       * @return This builder for chaining.
       */
      public Builder setLeaderId(long value) {
        
        leaderId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 leaderId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLeaderId() {
        
        leaderId_ = 0L;
        onChanged();
        return this;
      }

      private long lastLogIndex_ ;
      /**
       * <code>uint64 lastLogIndex = 3;</code>
       * @return The lastLogIndex.
       */
      @Override
      public long getLastLogIndex() {
        return lastLogIndex_;
      }
      /**
       * <code>uint64 lastLogIndex = 3;</code>
       * @param value The lastLogIndex to set.
       * @return This builder for chaining.
       */
      public Builder setLastLogIndex(long value) {
        
        lastLogIndex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 lastLogIndex = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearLastLogIndex() {
        
        lastLogIndex_ = 0L;
        onChanged();
        return this;
      }

      private long lastLogTerm_ ;
      /**
       * <code>uint64 lastLogTerm = 4;</code>
       * @return The lastLogTerm.
       */
      @Override
      public long getLastLogTerm() {
        return lastLogTerm_;
      }
      /**
       * <code>uint64 lastLogTerm = 4;</code>
       * @param value The lastLogTerm to set.
       * @return This builder for chaining.
       */
      public Builder setLastLogTerm(long value) {
        
        lastLogTerm_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 lastLogTerm = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearLastLogTerm() {
        
        lastLogTerm_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString configuration_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes configuration = 5;</code>
       * @return The configuration.
       */
      @Override
      public com.google.protobuf.ByteString getConfiguration() {
        return configuration_;
      }
      /**
       * <code>bytes configuration = 5;</code>
       * @param value The configuration to set.
       * @return This builder for chaining.
       */
      public Builder setConfiguration(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        configuration_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes configuration = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearConfiguration() {
        
        configuration_ = getDefaultInstance().getConfiguration();
        onChanged();
        return this;
      }

      private long configurationIndex_ ;
      /**
       * <code>uint64 configurationIndex = 6;</code>
       * @return The configurationIndex.
       */
      @Override
      public long getConfigurationIndex() {
        return configurationIndex_;
      }
      /**
       * <code>uint64 configurationIndex = 6;</code>
       * @param value The configurationIndex to set.
       * @return This builder for chaining.
       */
      public Builder setConfigurationIndex(long value) {
        
        configurationIndex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 configurationIndex = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearConfigurationIndex() {
        
        configurationIndex_ = 0L;
        onChanged();
        return this;
      }

      private long size_ ;
      /**
       * <code>uint64 size = 7;</code>
       * @return The size.
       */
      @Override
      public long getSize() {
        return size_;
      }
      /**
       * <code>uint64 size = 7;</code>
       * @param value The size to set.
       * @return This builder for chaining.
       */
      public Builder setSize(long value) {
        
        size_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 size = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearSize() {
        
        size_ = 0L;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:raft.InstallSnapshotRequest)
    }

    // @@protoc_insertion_point(class_scope:raft.InstallSnapshotRequest)
    private static final InstallSnapshotRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new InstallSnapshotRequest();
    }

    public static InstallSnapshotRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<InstallSnapshotRequest>
        PARSER = new com.google.protobuf.AbstractParser<InstallSnapshotRequest>() {
      @Override
      public InstallSnapshotRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new InstallSnapshotRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<InstallSnapshotRequest> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<InstallSnapshotRequest> getParserForType() {
      return PARSER;
    }

    @Override
    public InstallSnapshotRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface InstallSnapshotResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:raft.InstallSnapshotResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint64 term = 1;</code>
     * @return The term.
     */
    long getTerm();

    /**
     * <code>bool success = 2;</code>
     * @return The success.
     */
    boolean getSuccess();
  }
  /**
   * Protobuf type {@code raft.InstallSnapshotResponse}
   */
  public static final class InstallSnapshotResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:raft.InstallSnapshotResponse)
      InstallSnapshotResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use InstallSnapshotResponse.newBuilder() to construct.
    private InstallSnapshotResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private InstallSnapshotResponse() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new InstallSnapshotResponse();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private InstallSnapshotResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              term_ = input.readUInt64();
              break;
            }
            case 16: {

              success_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return InstallSnapshot.internal_static_raft_InstallSnapshotResponse_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return InstallSnapshot.internal_static_raft_InstallSnapshotResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              InstallSnapshotResponse.class, Builder.class);
    }

    public static final int TERM_FIELD_NUMBER = 1;
    private long term_;
    /**
     * <code>uint64 term = 1;</code>
     * @return The term.
     */
    @Override
    public long getTerm() {
      return term_;
    }

    public static final int SUCCESS_FIELD_NUMBER = 2;
    private boolean success_;
    /**
     * <code>bool success = 2;</code>
     * @return The success.
     */
    @Override
    public boolean getSuccess() {
      return success_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (term_ != 0L) {
        output.writeUInt64(1, term_);
      }
      if (success_ != false) {
        output.writeBool(2, success_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (term_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, term_);
      }
      if (success_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, success_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof InstallSnapshotResponse)) {
        return super.equals(obj);
      }
      InstallSnapshotResponse other = (InstallSnapshotResponse) obj;

      if (getTerm()
          != other.getTerm()) return false;
      if (getSuccess()
          != other.getSuccess()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TERM_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTerm());
      hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSuccess());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static InstallSnapshotResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static InstallSnapshotResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static InstallSnapshotResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static InstallSnapshotResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static InstallSnapshotResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static InstallSnapshotResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static InstallSnapshotResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static InstallSnapshotResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static InstallSnapshotResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static InstallSnapshotResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static InstallSnapshotResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static InstallSnapshotResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(InstallSnapshotResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code raft.InstallSnapshotResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:raft.InstallSnapshotResponse)
        InstallSnapshotResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return InstallSnapshot.internal_static_raft_InstallSnapshotResponse_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return InstallSnapshot.internal_static_raft_InstallSnapshotResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                InstallSnapshotResponse.class, Builder.class);
      }

      // Construct using com.github.cn.ccj.rpc.InstallSnapshot.InstallSnapshotResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        term_ = 0L;

        success_ = false;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return InstallSnapshot.internal_static_raft_InstallSnapshotResponse_descriptor;
      }

      @Override
      public InstallSnapshotResponse getDefaultInstanceForType() {
        return InstallSnapshotResponse.getDefaultInstance();
      }

      @Override
      public InstallSnapshotResponse build() {
        InstallSnapshotResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public InstallSnapshotResponse buildPartial() {
        InstallSnapshotResponse result = new InstallSnapshotResponse(this);
        result.term_ = term_;
        result.success_ = success_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof InstallSnapshotResponse) {
          return mergeFrom((InstallSnapshotResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(InstallSnapshotResponse other) {
        if (other == InstallSnapshotResponse.getDefaultInstance()) return this;
        if (other.getTerm() != 0L) {
          setTerm(other.getTerm());
        }
        if (other.getSuccess() != false) {
          setSuccess(other.getSuccess());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        InstallSnapshotResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (InstallSnapshotResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long term_ ;
      /**
       * <code>uint64 term = 1;</code>
       * @return The term.
       */
      @Override
      public long getTerm() {
        return term_;
      }
      /**
       * <code>uint64 term = 1;</code>
       * @param value The term to set.
       * @return This builder for chaining.
       */
      public Builder setTerm(long value) {
        
        term_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 term = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTerm() {
        
        term_ = 0L;
        onChanged();
        return this;
      }

      private boolean success_ ;
      /**
       * <code>bool success = 2;</code>
       * @return The success.
       */
      @Override
      public boolean getSuccess() {
        return success_;
      }
      /**
       * <code>bool success = 2;</code>
       * @param value The success to set.
       * @return This builder for chaining.
       */
      public Builder setSuccess(boolean value) {
        
        success_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool success = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSuccess() {
        
        success_ = false;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:raft.InstallSnapshotResponse)
    }

    // @@protoc_insertion_point(class_scope:raft.InstallSnapshotResponse)
    private static final InstallSnapshotResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new InstallSnapshotResponse();
    }

    public static InstallSnapshotResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<InstallSnapshotResponse>
        PARSER = new com.google.protobuf.AbstractParser<InstallSnapshotResponse>() {
      @Override
      public InstallSnapshotResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new InstallSnapshotResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<InstallSnapshotResponse> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<InstallSnapshotResponse> getParserForType() {
      return PARSER;
    }

    @Override
    public InstallSnapshotResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_raft_InstallSnapshotRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_raft_InstallSnapshotRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_raft_InstallSnapshotResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_raft_InstallSnapshotResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\025InstallSnapshot.proto\022\004raft\"\244\001\n\026Instal" +
      "lSnapshotRequest\022\014\n\004term\030\001 \001(\004\022\020\n\010leader" +
      "Id\030\002 \001(\004\022\024\n\014lastLogIndex\030\003 \001(\004\022\023\n\013lastLo" +
      "gTerm\030\004 \001(\004\022\025\n\rconfiguration\030\005 \001(\014\022\032\n\022co" +
      "nfigurationIndex\030\006 \001(\004\022\014\n\004size\030\007 \001(\004\"8\n\027" +
      "InstallSnapshotResponse\022\014\n\004term\030\001 \001(\004\022\017\n" +
      "\007success\030\002 \001(\0102h\n\026InstallSnapshotService" +
      "\022N\n\017installSnapshot\022\034.raft.InstallSnapsh" +
      "otRequest\032\035.raft.InstallSnapshotResponse" +
      "B\031\n\025com.github.cn.ccj.rpcP\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_raft_InstallSnapshotRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_raft_InstallSnapshotRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_raft_InstallSnapshotRequest_descriptor,
        new String[] { "Term", "LeaderId", "LastLogIndex", "LastLogTerm", "Configuration", "ConfigurationIndex", "Size", });
    internal_static_raft_InstallSnapshotResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_raft_InstallSnapshotResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_raft_InstallSnapshotResponse_descriptor,
        new String[] { "Term", "Success", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
