// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RequestVote.proto

package com.github.cn.ccj.rpc;

public final class RequestVote {
  private RequestVote() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface VoteRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:raft.VoteRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint64 term = 1;</code>
     * @return The term.
     */
    long getTerm();

    /**
     * <code>uint64 candidateId = 2;</code>
     * @return The candidateId.
     */
    long getCandidateId();

    /**
     * <code>uint64 lastLogIndex = 3;</code>
     * @return The lastLogIndex.
     */
    long getLastLogIndex();

    /**
     * <code>uint64 lastLogTerm = 4;</code>
     * @return The lastLogTerm.
     */
    long getLastLogTerm();
  }
  /**
   * Protobuf type {@code raft.VoteRequest}
   */
  public static final class VoteRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:raft.VoteRequest)
      VoteRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use VoteRequest.newBuilder() to construct.
    private VoteRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private VoteRequest() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new VoteRequest();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private VoteRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              term_ = input.readUInt64();
              break;
            }
            case 16: {

              candidateId_ = input.readUInt64();
              break;
            }
            case 24: {

              lastLogIndex_ = input.readUInt64();
              break;
            }
            case 32: {

              lastLogTerm_ = input.readUInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RequestVote.internal_static_raft_VoteRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RequestVote.internal_static_raft_VoteRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              VoteRequest.class, Builder.class);
    }

    public static final int TERM_FIELD_NUMBER = 1;
    private long term_;
    /**
     * <code>uint64 term = 1;</code>
     * @return The term.
     */
    @Override
    public long getTerm() {
      return term_;
    }

    public static final int CANDIDATEID_FIELD_NUMBER = 2;
    private long candidateId_;
    /**
     * <code>uint64 candidateId = 2;</code>
     * @return The candidateId.
     */
    @Override
    public long getCandidateId() {
      return candidateId_;
    }

    public static final int LASTLOGINDEX_FIELD_NUMBER = 3;
    private long lastLogIndex_;
    /**
     * <code>uint64 lastLogIndex = 3;</code>
     * @return The lastLogIndex.
     */
    @Override
    public long getLastLogIndex() {
      return lastLogIndex_;
    }

    public static final int LASTLOGTERM_FIELD_NUMBER = 4;
    private long lastLogTerm_;
    /**
     * <code>uint64 lastLogTerm = 4;</code>
     * @return The lastLogTerm.
     */
    @Override
    public long getLastLogTerm() {
      return lastLogTerm_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (term_ != 0L) {
        output.writeUInt64(1, term_);
      }
      if (candidateId_ != 0L) {
        output.writeUInt64(2, candidateId_);
      }
      if (lastLogIndex_ != 0L) {
        output.writeUInt64(3, lastLogIndex_);
      }
      if (lastLogTerm_ != 0L) {
        output.writeUInt64(4, lastLogTerm_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (term_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, term_);
      }
      if (candidateId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, candidateId_);
      }
      if (lastLogIndex_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, lastLogIndex_);
      }
      if (lastLogTerm_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, lastLogTerm_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof VoteRequest)) {
        return super.equals(obj);
      }
      VoteRequest other = (VoteRequest) obj;

      if (getTerm()
          != other.getTerm()) return false;
      if (getCandidateId()
          != other.getCandidateId()) return false;
      if (getLastLogIndex()
          != other.getLastLogIndex()) return false;
      if (getLastLogTerm()
          != other.getLastLogTerm()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TERM_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTerm());
      hash = (37 * hash) + CANDIDATEID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCandidateId());
      hash = (37 * hash) + LASTLOGINDEX_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLastLogIndex());
      hash = (37 * hash) + LASTLOGTERM_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLastLogTerm());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static VoteRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static VoteRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static VoteRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static VoteRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static VoteRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static VoteRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static VoteRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static VoteRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static VoteRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static VoteRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static VoteRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static VoteRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(VoteRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code raft.VoteRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:raft.VoteRequest)
        VoteRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return RequestVote.internal_static_raft_VoteRequest_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return RequestVote.internal_static_raft_VoteRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                VoteRequest.class, Builder.class);
      }

      // Construct using com.github.cn.ccj.rpc.RequestVote.VoteRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        term_ = 0L;

        candidateId_ = 0L;

        lastLogIndex_ = 0L;

        lastLogTerm_ = 0L;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return RequestVote.internal_static_raft_VoteRequest_descriptor;
      }

      @Override
      public VoteRequest getDefaultInstanceForType() {
        return VoteRequest.getDefaultInstance();
      }

      @Override
      public VoteRequest build() {
        VoteRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public VoteRequest buildPartial() {
        VoteRequest result = new VoteRequest(this);
        result.term_ = term_;
        result.candidateId_ = candidateId_;
        result.lastLogIndex_ = lastLogIndex_;
        result.lastLogTerm_ = lastLogTerm_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof VoteRequest) {
          return mergeFrom((VoteRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(VoteRequest other) {
        if (other == VoteRequest.getDefaultInstance()) return this;
        if (other.getTerm() != 0L) {
          setTerm(other.getTerm());
        }
        if (other.getCandidateId() != 0L) {
          setCandidateId(other.getCandidateId());
        }
        if (other.getLastLogIndex() != 0L) {
          setLastLogIndex(other.getLastLogIndex());
        }
        if (other.getLastLogTerm() != 0L) {
          setLastLogTerm(other.getLastLogTerm());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        VoteRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (VoteRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long term_ ;
      /**
       * <code>uint64 term = 1;</code>
       * @return The term.
       */
      @Override
      public long getTerm() {
        return term_;
      }
      /**
       * <code>uint64 term = 1;</code>
       * @param value The term to set.
       * @return This builder for chaining.
       */
      public Builder setTerm(long value) {
        
        term_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 term = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTerm() {
        
        term_ = 0L;
        onChanged();
        return this;
      }

      private long candidateId_ ;
      /**
       * <code>uint64 candidateId = 2;</code>
       * @return The candidateId.
       */
      @Override
      public long getCandidateId() {
        return candidateId_;
      }
      /**
       * <code>uint64 candidateId = 2;</code>
       * @param value The candidateId to set.
       * @return This builder for chaining.
       */
      public Builder setCandidateId(long value) {
        
        candidateId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 candidateId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCandidateId() {
        
        candidateId_ = 0L;
        onChanged();
        return this;
      }

      private long lastLogIndex_ ;
      /**
       * <code>uint64 lastLogIndex = 3;</code>
       * @return The lastLogIndex.
       */
      @Override
      public long getLastLogIndex() {
        return lastLogIndex_;
      }
      /**
       * <code>uint64 lastLogIndex = 3;</code>
       * @param value The lastLogIndex to set.
       * @return This builder for chaining.
       */
      public Builder setLastLogIndex(long value) {
        
        lastLogIndex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 lastLogIndex = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearLastLogIndex() {
        
        lastLogIndex_ = 0L;
        onChanged();
        return this;
      }

      private long lastLogTerm_ ;
      /**
       * <code>uint64 lastLogTerm = 4;</code>
       * @return The lastLogTerm.
       */
      @Override
      public long getLastLogTerm() {
        return lastLogTerm_;
      }
      /**
       * <code>uint64 lastLogTerm = 4;</code>
       * @param value The lastLogTerm to set.
       * @return This builder for chaining.
       */
      public Builder setLastLogTerm(long value) {
        
        lastLogTerm_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 lastLogTerm = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearLastLogTerm() {
        
        lastLogTerm_ = 0L;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:raft.VoteRequest)
    }

    // @@protoc_insertion_point(class_scope:raft.VoteRequest)
    private static final VoteRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new VoteRequest();
    }

    public static VoteRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<VoteRequest>
        PARSER = new com.google.protobuf.AbstractParser<VoteRequest>() {
      @Override
      public VoteRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new VoteRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<VoteRequest> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<VoteRequest> getParserForType() {
      return PARSER;
    }

    @Override
    public VoteRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface VoteResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:raft.VoteResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint64 term = 1;</code>
     * @return The term.
     */
    long getTerm();

    /**
     * <code>bool voteGranted = 2;</code>
     * @return The voteGranted.
     */
    boolean getVoteGranted();
  }
  /**
   * Protobuf type {@code raft.VoteResponse}
   */
  public static final class VoteResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:raft.VoteResponse)
      VoteResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use VoteResponse.newBuilder() to construct.
    private VoteResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private VoteResponse() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new VoteResponse();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private VoteResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              term_ = input.readUInt64();
              break;
            }
            case 16: {

              voteGranted_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RequestVote.internal_static_raft_VoteResponse_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RequestVote.internal_static_raft_VoteResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              VoteResponse.class, Builder.class);
    }

    public static final int TERM_FIELD_NUMBER = 1;
    private long term_;
    /**
     * <code>uint64 term = 1;</code>
     * @return The term.
     */
    @Override
    public long getTerm() {
      return term_;
    }

    public static final int VOTEGRANTED_FIELD_NUMBER = 2;
    private boolean voteGranted_;
    /**
     * <code>bool voteGranted = 2;</code>
     * @return The voteGranted.
     */
    @Override
    public boolean getVoteGranted() {
      return voteGranted_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (term_ != 0L) {
        output.writeUInt64(1, term_);
      }
      if (voteGranted_ != false) {
        output.writeBool(2, voteGranted_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (term_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, term_);
      }
      if (voteGranted_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, voteGranted_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof VoteResponse)) {
        return super.equals(obj);
      }
      VoteResponse other = (VoteResponse) obj;

      if (getTerm()
          != other.getTerm()) return false;
      if (getVoteGranted()
          != other.getVoteGranted()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TERM_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTerm());
      hash = (37 * hash) + VOTEGRANTED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getVoteGranted());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static VoteResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static VoteResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static VoteResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static VoteResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static VoteResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static VoteResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static VoteResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static VoteResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static VoteResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static VoteResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static VoteResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static VoteResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(VoteResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code raft.VoteResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:raft.VoteResponse)
        VoteResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return RequestVote.internal_static_raft_VoteResponse_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return RequestVote.internal_static_raft_VoteResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                VoteResponse.class, Builder.class);
      }

      // Construct using com.github.cn.ccj.rpc.RequestVote.VoteResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        term_ = 0L;

        voteGranted_ = false;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return RequestVote.internal_static_raft_VoteResponse_descriptor;
      }

      @Override
      public VoteResponse getDefaultInstanceForType() {
        return VoteResponse.getDefaultInstance();
      }

      @Override
      public VoteResponse build() {
        VoteResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public VoteResponse buildPartial() {
        VoteResponse result = new VoteResponse(this);
        result.term_ = term_;
        result.voteGranted_ = voteGranted_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof VoteResponse) {
          return mergeFrom((VoteResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(VoteResponse other) {
        if (other == VoteResponse.getDefaultInstance()) return this;
        if (other.getTerm() != 0L) {
          setTerm(other.getTerm());
        }
        if (other.getVoteGranted() != false) {
          setVoteGranted(other.getVoteGranted());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        VoteResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (VoteResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long term_ ;
      /**
       * <code>uint64 term = 1;</code>
       * @return The term.
       */
      @Override
      public long getTerm() {
        return term_;
      }
      /**
       * <code>uint64 term = 1;</code>
       * @param value The term to set.
       * @return This builder for chaining.
       */
      public Builder setTerm(long value) {
        
        term_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 term = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTerm() {
        
        term_ = 0L;
        onChanged();
        return this;
      }

      private boolean voteGranted_ ;
      /**
       * <code>bool voteGranted = 2;</code>
       * @return The voteGranted.
       */
      @Override
      public boolean getVoteGranted() {
        return voteGranted_;
      }
      /**
       * <code>bool voteGranted = 2;</code>
       * @param value The voteGranted to set.
       * @return This builder for chaining.
       */
      public Builder setVoteGranted(boolean value) {
        
        voteGranted_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool voteGranted = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearVoteGranted() {
        
        voteGranted_ = false;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:raft.VoteResponse)
    }

    // @@protoc_insertion_point(class_scope:raft.VoteResponse)
    private static final VoteResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new VoteResponse();
    }

    public static VoteResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<VoteResponse>
        PARSER = new com.google.protobuf.AbstractParser<VoteResponse>() {
      @Override
      public VoteResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new VoteResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<VoteResponse> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<VoteResponse> getParserForType() {
      return PARSER;
    }

    @Override
    public VoteResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_raft_VoteRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_raft_VoteRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_raft_VoteResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_raft_VoteResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021RequestVote.proto\022\004raft\"[\n\013VoteRequest" +
      "\022\014\n\004term\030\001 \001(\004\022\023\n\013candidateId\030\002 \001(\004\022\024\n\014l" +
      "astLogIndex\030\003 \001(\004\022\023\n\013lastLogTerm\030\004 \001(\004\"1" +
      "\n\014VoteResponse\022\014\n\004term\030\001 \001(\004\022\023\n\013voteGran" +
      "ted\030\002 \001(\0102<\n\013VoteService\022-\n\004vote\022\021.raft." +
      "VoteRequest\032\022.raft.VoteResponseB\031\n\025com.g" +
      "ithub.cn.ccj.rpcP\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_raft_VoteRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_raft_VoteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_raft_VoteRequest_descriptor,
        new String[] { "Term", "CandidateId", "LastLogIndex", "LastLogTerm", });
    internal_static_raft_VoteResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_raft_VoteResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_raft_VoteResponse_descriptor,
        new String[] { "Term", "VoteGranted", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
